### ISSUE TITLE
Consistent server crash - using a modpack

### ISSUE THREAD

**Issue by HellsReindeer** [CmdrJane/Discordium#5]
I've got a server setup for better minecraft 1.18.1, right up to when it loads the mod the server will immediately crash and give me this
(no crash report is being generated for some reason)

I'm pretty sure I have the correct configuration setup, it used to throw me some errors telling me I was missing the token and such but I already got all that sorted out now

[10:21:18] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'discordium'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.13.2.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.2.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.2.jar:?]
Caused by: java.lang.IllegalArgumentException: ID may not be empty
        at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:77) ~[net_dv8tion_jda-5.0.0-alpha.1-775936ed1afaf8aa.jar:?]
        at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:115) ~[net_dv8tion_jda-5.0.0-alpha.1-775936ed1afaf8aa.jar:?]
        at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59) ~[net_dv8tion_jda-5.0.0-alpha.1-775936ed1afaf8aa.jar:?]
        at net.dv8tion.jda.api.JDA.getTextChannelById(JDA.java:1807) ~[net_dv8tion_jda-5.0.0-alpha.1-775936ed1afaf8aa.jar:?]
        at ru.aiefu.discordium.discord.DiscordLink.initialize(DiscordLink.java:123) ~[discordium-1.1.2+1.18.1.jar:?]
        at ru.aiefu.discordium.discord.DiscordLink.onInitializeServer(DiscordLink.java:75) ~[discordium-1.1.2+1.18.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.2.jar:?]
        ... 15 more

**Comment by CmdrJane** [comment]
This is not a bug. Read [wiki ](https://github.com/CmdrJane/Discordium/wiki)for full setup guide
