### ISSUE TITLE
server side crash.

### ISSUE THREAD

**Issue by netcore10** [CmdrJane/Discordium#8]
java.lang.RuntimeExceptionCould not execute entrypoint stage 'server' due to errors, provided by 'discordium'!
[10.05 16:19:22] [Server] 	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
[10.05 16:19:22] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[10.05 16:19:22] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[10.05 16:19:22] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[10.05 16:19:22] [Server] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[10.05 16:19:22] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[10.05 16:19:22] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[10.05 16:19:22] [Server] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] Caused byjava.lang.IllegalArgumentException: ID may not be empty
[10.05 16:19:22] [Server] 	at net.dv8tion.jda.internal.utils.Checks.notEmpty(Checks.java:77) ~[net_dv8tion_jda-5.0.0-alpha.1-f20fc53175c20a96.jar:?]
[10.05 16:19:22] [Server] 	at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:115) ~[net_dv8tion_jda-5.0.0-alpha.1-f20fc53175c20a96.jar:?]
[10.05 16:19:22] [Server] 	at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59) ~[net_dv8tion_jda-5.0.0-alpha.1-f20fc53175c20a96.jar:?]
[10.05 16:19:22] [Server] 	at net.dv8tion.jda.api.JDA.getTextChannelById(JDA.java:1807) ~[net_dv8tion_jda-5.0.0-alpha.1-f20fc53175c20a96.jar:?]
[10.05 16:19:22] [Server] 	at ru.aiefu.discordium.discord.DiscordLink.initialize(DiscordLink.java:127) ~[discordium-1.1.4+1.18.2.jar:?]
[10.05 16:19:22] [Server] 	at ru.aiefu.discordium.discord.DiscordLink.onInitializeServer(DiscordLink.java:78) ~[discordium-1.1.4+1.18.2.jar:?]
[10.05 16:19:22] [Server] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
[10.05 16:19:22] [Server] 	... more

**Comment by CmdrJane** [comment]
read [wiki](https://github.com/CmdrJane/Discordium/wiki) for full setup guide
